package com.naruto.system.domain;

public enum JutsuTipo {
    NINJUTSU, TAIJUTSU, GENJUTSU,
    FUUINJUTSU, KENJUTSU, SENJUTSU, ESPACIO_TIEMPO, NINTAIJUTSU, MEDICO, BARRERA,
    DOJUTSU, KEKKEI_GENKAI, KEKKEI_TOTA, KEKKEI_MORA,
    ABSORCION_CHAKRA, COLABORACION, CLONACION, INVOCACION, SELLADO
}
